name: example
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: ">=3.8.0 <4.0.0"

dependencies:
  chopper: 8.4.0
  collection: 1.19.1
  dio: ^5.9.0
  freezed_annotation: ^3.1.0
  http: 1.5.0
  json_annotation: 4.9.0
  retrofit: ^4.9.2

dev_dependencies:
  swagger_dart_code_generator:
    path: ../
  chopper_generator: 8.5.0
  build_runner: ^2.10.5
  json_serializable: 6.11.3
  lints: 6.0.0
  retrofit_generator: ^10.2.1
  freezed: ^3.2.4
